- name: restart kubelet
  service: 
    name: kubelet 
    state: restarted 
    daemon_reload: yes

- name: restart containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes

- name: restart service docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    
- name: docker status
  service: 
    name: docker 
    state: started